---
title: "Current Projects"
output: html_document
---

---

## Working Papers

1. ### Bank Risk Sentiment 

   Abstract: This paper evaluates the role of investor risk sentiments in the commercial bank lending market and their effect on macroeconomic outcomes. I create an empirical measure of bank risk sentiment ---irrational bank-level shocks to expected loan portfolio default rates--- using regulatory data covering the universe of U.S. commercial banks and an identification scheme motivated by a novel, analytical, heterogeneous bank model. Aggregate bank risk sentiment (BRS) is pessimistic during financial crises and optimistic during debt-fueled asset bubbles, but is heterogeneous at the bank-level. BRS shocks act like credit supply shocks, impacting both the extensive and intensive margins of lending. Through lending markets, a pessimistic sentiment shock leads to a significant and long-lived deterioration in economic activity and prices, prompting a monetary policy easing. I also show that BRS is equally or more important in explaining macroeconomic outcomes than corporate bond market sentiment shocks (proxied by fluctuations in the Excess Bond Premium), real shocks (including generic aggregate demand and supply shocks), and U.S. monetary policy shocks. I lastly turn to a loan-level analysis to explore the potential micro-to-macro transmission mechanisms of bank-level sentiment shocks, and show that pessimistic sentiment shocks tighten earning base borrowing constraints. 
   
   [Working paper (August 2024)](./content/Pike - Bank Risk Sentiment - Summer 2024.pdf)


2. ### Bank Lending Standards and the U.S. Economy

   Coauthored with Elijah Broadbent,  [Huberto Ennis](https://www.richmondfed.org/research/people/ennis), and [Horacio Sapriza](https://www.richmondfed.org/research/people/sapriza)  
   
   Abstract: The provision of bank credit to firms and households affects macroeconomic performance. We use survey measures of changes in bank lending standards, disaggregated by loan category, to quantify the effect of changes in banks’ attitudes toward lending on aggregate output, inflation, and interest rates. Bank lending to businesses is particularly important for macroeconomic outcomes, with peak effects on output of around half a percentage point after four quarters of the initial shock. These effects depend on the stage of the business cycle and the proximity of the short-term interest rate to its effective lower bound. The effects are larger when output is growing below trend and when the interest rate is away from its lower bound. We also find that the response of the economy to lending-standards shocks is asymmetric, with tightening shocks having larger effects on output. 
   
   [FRB Richmond WP (August 2024)](https://www.richmondfed.org/publications/research/working_papers/2024/wp_24-07)

## Works in progress

1. ### Getting in all the Cracks: Monetary Policy, Financial Vulnerabilities, and Macro Risk

   Coauthored with [Andrea Ajello](https://sites.google.com/site/ajelloandrea/)
   
   Abstract: We estimate the effect of monetary policy on financial vulnerabilities and the implications for macroeconomic tail risk. We first extract a small set of common factors from a large dataset of financial vulnerability indicators, estimating a factor-augmented proxy SVAR to study the response of aggregate economic activity, inflation, and financial vulnerabilities to monetary policy shocks. We then estimate the effect of changes in the financial vulnerability factors on macroeconomic tail risk via quantile regressions. We find that an unexpected monetary policy tightening can lower asset valuation vulnerabilities in the short term and slow down credit growth in the medium term. As tighter monetary policy reduces asset valuation pressures, it does so at a cost of a sizable increase in macro tail risk in the short term that is only partially offset by a modest reduction in tail risk in the medium term, induced by a slowdown in credit growth.


2. ### Uncertainty Shocks and Market Concentration     

   Abstract: This paper studies the relationship between productivity uncertainty shocks and sales concentration. In one direction, uncertainty shocks cause a persistent increase in concentration. Empirically, a one standard deviation uncertainty shock induces a persistent 7.65 percent rise in concentration (as measured by the HHI of US public firms) that does not recover for at least eight years after the shock. However, a heterogeneous firm model with standard productivity uncertainty transmission channels and calibrated to US data cannot replicate the persistence of the empirical relationship. I propose the addition of an entrepreneurial funding channel and show that incorporating the impact of uncertainty on firm entry is key to matching the data. In the other direction, the quantitative model shows that the pre-existing level of concentration mediates the transmission of uncertainty shocks to the broader economy by dampening the financial accelerator's amplification of the shock. The intuition is that the more concentrated an economy is, the more activity is controlled by firms largely unaffected by financial constraints, ameliorating the effects of credit supply distributions. The relationship between uncertainty and concentration has a number of implications for the medium and long run costs of cyclical shocks and can help explain the simultaneous secular decline in business dynamism and increase in firm-level uncertainty observed in the United States.
