---
title: Packages
output: html_document
---

## 1. Out-Of-Sample Time Series Forecasting Workbench
This package creates a paradigm to provide a structured and automatd approach to out-of-sample time series forecasting, a common, important, and subtle task. In many ways, this package is merely a wrapper for the excellent exant time series forecasting routines on CRAN -- including both traditional econometric time series models and modern machine learning techniques. However, this package additionally provides a modern and comprehensive set of forecast combination tools and forecast comparison metrics.  

[Github](https://github.com/tylerJPike/OOS)

## 2. Tree-Based Impulse Response Functions  
This package produces and plots tree-based impulse response functions. Users may choose from two random forest variants, implement instrumental variable, allow state-dependence, and choose lags based on information criteria or forecasting accuracy.   

[GitHub](https://github.com/tylerJPike/treeImpulses)  